---
title: SugarWanderLust
baseURL: "/"
params:
  layout_style: overflow
  palette: blue
  header:
    title: SugarWanderLust
    tagline: I'm the best!
    profile_img: images/avatar.png
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links: []
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
